import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { NavBar } from '@/components/NavBar'
import { FC, PropsWithChildren } from 'react'

const inter = Inter({ subsets: ['latin'] })

interface Props {
  title: string;
}


export const MainLayout: FC <PropsWithChildren <Props>>  = ({children, title}) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={`${styles.main} ${inter.className}`}>
        {children}
      </main>
    </>
  )
}
